baseurl = "http://everything-as-code.de/"
languageCode = "de-de"
title = "Everything as Code"

theme = "startbootstrap-clean-blog"
copyright = "Code released under the Apache 2.0 license."

[author]
  name = "Everything-as-code"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Your site description"
  Author = "Benoît Benedetti"
  email = "everything.as.code@gmail.com"


[[params.social]]
  title = "twitter"
  url = "https://twitter.com/E_as_C"
[[params.social]]
  title = "github"
  url = "https://github.com/devulrix"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "slack"
  url = "/slack.html"
  weight = -180
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -160
