baseurl = "http://www.everything-as-code.de"
languageCode = "de-de"
title = "Everything as Code"

theme = "startbootstrap-clean-blog"
copyright = "Code released under the Apache 2.0 license."

[author]
  name = "Everything-as-code"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "A blog for livelong learners"
  Author = "Everything-as-code"
  email = "everything.as.code@gmail.com"
  MainBGImage = "/images/main_bg.jpg"


[[params.social]]
  title = "twitter"
  url = "https://twitter.com/E_as_C"
[[params.social]]
  title = "github"
  url = "https://github.com/devulrix"
[[params.social]]
    title = "youtube"
    url = "https://www.youtube.com/channel/UC4d2lgIJa9FhQeVqUaFx1BQ/featured"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "YouTube"
  url = "https://www.youtube.com/channel/UC4d2lgIJa9FhQeVqUaFx1BQ/featured"
  weight = -180
[[menu.main]]
  name = "Twitter"
  url = "https://twitter.com/E_as_C"
  weight = -140
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -120
