baseURL = "https://everything-as-code.com"
languageCode = "en-us"
title = "Everyting as Code"
theme = "eac-theme"

[params]
    description = "A Blog for life long learners"
    # feature image for OpenGraph and Twitter
    images = ["site-feature-image.jpg"]