baseURL = "https://everything-as-code.com"
languageCode = "en-us"
title = "Everyting as Code"
theme = "eac-theme"
pagination.pagerSize = 6

enableGitInfo = true
enableEmoji = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[params]
    description = "A Blog for life long learners"
    # feature image for OpenGraph and Twitter
    images = ["logo-wide.svg"]
    author = "Ulrich Hölscher"
    authorDescription = "Advisory Platform Architect"
    authorImage = "/images/ulrich-small.webp"
    authorURL = "https://twitter.com/devulrix"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
      anchorLineNos = false
      codeFences = true
      guessSyntax = false
      hl_Lines = ''
      lineAnchors = ''
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = true
      noClasses = false
      style = 'monokailight'
      tabWidth = 4

# [permalinks]
#     blog = "/blog/:filename/"

[taxonomies]
  category = 'categories'
  series = 'series'

[related]
    threshold = 0 
    includeNewer = true
    toLower = true

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "date"
        weight = 10

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[[menu.main]]
  name = "Categories"
  url = "/categories"

#[[menu.main]]
#  name = "Series"
#  url = "/series"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/devulrix"
    pre = "<i class='fa-brands fa-github'></i>"

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UC4d2lgIJa9FhQeVqUaFx1BQ"
    pre = "<i class='fa-brands fa-youtube'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/devulrix"
    pre = "<i class='fa-brands fa-x-twitter'></i>"

[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Privacy"
  url = "/privacy"

[[menu.footer]]
  name = "Imprint"
  url = "/imprint"

# [[menu.footer]]
#   name = "Contact"
#   url = "/contact"