---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: klakegg/hugo
    username: ((docker-user))
    password: ((docker-password))

inputs:
    - name: source

outputs:
    - name: blog-depyloment

run:
  path: /bin/sh
  args: ["source/ci/scripts/build.sh"]