---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: klakegg/hugo

inputs:
    - name: source

outputs:
    - name: blog-deployment

run:
  path: /bin/sh
  args: ["source/ci/scripts/build.sh"]