platform: linux

image_resource:
    type: docker-image
    source: 
        repository: klakegg/hugo
        tag: 0.55.6

inputs: 
- name: eac-hugo
outputs:
- name: generted-website

run: 
    path: ci/tasks/hugo-build.sh
    dir: eac-hugo