---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ulrix/t-image

inputs:
- name: source
- name: blog-deployment

params:
    FTP_SERVER:
    FTP_USERNAME:
    FTP_PASSWORD:

run:
  path: /bin/sh
  args:
  - source/ci/scripts/publish.sh